### ISSUE TITLE
would you please create imgproxy.swf? 

### ISSUE THREAD

**Issue by crazyvalse** [thatguystone/imgproxy#1]
Hi! Thank you for the imgproxy! It appears able to handle my issue perfectly! However, it is hard for me to create the imgproxy.swf with .as files. 

Do you mind if you provide imgproxy.swf under the /src/html ?

Thanks a lot!

**Comment by thatguystone** [comment]
I haven't built this in 5 years, and I don't think I even have an AS SDK around anymore. Given that browsers are starting to retire flash support, you might be better suited using something like http://stackoverflow.com/a/16566198/2176216.
